apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: terraform-plan
spec:
  params:
    # These may be overridden, but provide sensible defaults.
    - name: directory
      type: string
      description: The directory containing the build context.
      default: /workspace
  outputs:
  steps:
    - name: terraform init
      image: blokje5/terraform-aws:latest
      workingDir: "$(inputs.params.directory)"
      args: [
        "init"
      ]
    - name: terraform plan
      image: blokje5/terraform-aws:latest
      workingDir: "$(inputs.params.directory)"
      args: [
        "plan",
        "-out=tfplan"
      ]
    - name: terraform plan
      image: blokje5/terraform-aws:latest
      workingDir: "$(inputs.params.directory)"
      args: [
        "plan",
        "-json",
        ""./tfplan", 
        ">", 
        "tfplan.json"
      ]
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-secret
            key: key
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-secret
            key: secret