apiVersion: v1
kind: Pod
metadata:
  name: docker-registry
  labels:
    run: docker-registry
spec:
  containers:
  - image: registry
    name: docker-registry
    ports:
    - containerPort: 5000
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - image: nginx
    name: nginx-proxy
    ports:
    - containerPort: 443
    volumeMounts:
    - name: secret-volume
      mountPath: /app/cert
    - name: config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  volumes:
  - name: cache-volume
    emptyDir: {}
  - name: secret-volume
    secret:
      secretName: nginx-certs
      items:
        - key: cert
          path: docker-registry.pem
        - key: key
          path: docker-registry-key.pem
  - name: config-volume
    configMap:
      name: nginx-conf
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: docker-registry
# spec:
#   ports:
#   - port: 443
#     protocol: TCP
#   selector:
#     run: docker-registry
apiVersion: v1
kind: Service
metadata:
  labels:
    run: docker-registry
  name: docker-registry
spec:
  type: NodePort
  selector:
    run: docker-registry
  ports:
  - name: "registry"
    port: 5000
    targetPort: 5000
    nodePort: 32001