apiVersion: v1
kind: Pod
metadata:
  name: docker-registry
spec:
  containers:
  - image: registry
    name: docker-registry
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}